version: '3.4'

# Whenever possible use dynamic ports here and use fixed ports in docker-compose.override.yml

services:

  postgres:
    image: postgres:12.4
    ports:
      - "5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "mypassword"
      POSTGRES_DB: "dothebackend"