spring:
  main:
    banner-mode: "OFF"
    cloud-platform: kubernetes
  profiles:
    active: dev
  datasource:
    url: "jdbc:postgresql://${database.host}:${database.port}/${database.name}"
    username: "${database.username}"
    password: "${database.password}"
    driver-class-name: "org.postgresql.Driver"

database:
  host: "localhost"
  port: 5432
  name: "tddworkshop"
  username: "root"
  password: "mypassword"
